{
 "title": "Nginx",
 "description": "Nginx exporter metrics",
 "tags": [ "nginx" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_connections_processed_total{stage=\"any\"}[5m])) by (stage)",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_connections_current) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connections rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_connections_processed_total{stage!=\"any\"}[5m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Nginx up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_up", "legendFormat": "nginx" }
   ]
  }
 ]
}